### ISSUE TITLE
Updated an old Playthrough from 3.0.4.0 to latest 3.4.11F and now game won't launch

### ISSUE THREAD

**Issue by fxceptioN** [Cazadorsniper/PO3#1746]
# Use the search function before reporting to see if the issue has been reported before.
**Pack Version:** 3.4.11F
**Pack Mode (Normal, Titan, Kappa, Mythic):** KAPPA
**Singleplayer, Multiplayer, or LAN?:** Singleplayer

**Description:** I tried launching the game after upgrading the pack, and it just crashes on startup.

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/ReflectionUtil

**Steps to reproduce:** Launch the game after updating from 3.0.4.0 to 3.4.11F

**Crash log (use pastebin or issue will be closed):** https://pastebin.com/Hs1fpX29

**Comment by Cazadorsniper** [comment]
Reinstall the pack, all the mods aren't there.

**Comment by fxceptioN** [comment]
I managed to reinstall the pack and am able to connect to the world however, it won't let me claim unclaimed rewards. When I click on claim reward it does absolutely nothing.

**Comment by Cazadorsniper** [comment]
That old world maybe broken now due to mod updates and changes, you could try going into the world folder to find the BetterQuesting folder and deleting questprogress.json but that might cause you to start all over in terms of quests.

**Comment by fxceptioN** [comment]
It's UUID related and I cannot seem to figure it out.

**Comment by Cazadorsniper** [comment]
Its probably best to start over.

**Comment by fxceptioN** [comment]
I'm going to close the ticket. I figured out the issue and fixed it. Thanks!
